### ISSUE TITLE
What separator to use for the cache

### ISSUE THREAD

**Issue by Nyholm** [php-cache/taggable-cache#16]
As discussed in #15. 

The only valid characters according to the spec are  `A-Z`, `a-z`, `0-9`, `_`, and `.`. 
The invalid characters are: `{}()/\@:`

We should not use a invalid character but not a valid either. The hierarchy uses "|". Suggestions: `, ! # + -= & % #`.

I think @matthiasmullie's idea of using exclamation mark sounds good.

**Comment by aequasi** [comment]
i like either ! or %

**Comment by Nyholm** [comment]
It is!
