### ISSUE TITLE
How to handle validateTagName error?

### ISSUE THREAD

**Issue by matthiasmullie** [php-cache/taggable-cache#20]
It's unclear what should happen when validateTagName encounters invalid characters in the name. I assume it would throw a Psr\Cache\InvalidArgumentException, but that should probably be added to the function's phpdoc:

`@throws \Psr\Cache\InvalidArgumentException`

https://github.com/php-cache/taggable-cache/blob/master/src/TaggablePoolTrait.php#L60

**Comment by Nyholm** [comment]
Agreed. An that line should change the example "tag:$name" to "tag!$name". 

Can you send a PR?

Comment Close and comment
