### ISSUE TITLE
Interface to typehint against

### ISSUE THREAD

**Issue by Nyholm** [php-cache/taggable-cache#23]
When I require a cache pool that has taggs in my app I would like to type hint against something that allow me to use tag but also include the `CacheItemPoolInterface::save`. 

I can't use `TaggablePoolInterface` since it does not have a save function. Is it a good solution to create an interface that extends both `TaggablePoolInterface` and `CacheItemPoolInterface` and make sure adapters implement the new interface?

**Comment by aequasi** [comment]
Should `TaggablePoolInterface` extend `CacheItemPoolInterface`?

**Comment by Nyholm** [comment]
Is that correct considering the interface segregation principle?

Hm, will an object ever implement `TaggablePoolInterface` but not `CacheItemPoolInterface`? Not likely but it is possible.
